version: "3"

services:
  kerlink-migration-tool:
    container_name: kerlink-migration-tool
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/:/data/
    environment:
      - URL=${URL}
      - AUTH=${AUTH}
